[package]
authors = ["PhotonQuantum <self@lightquantum.me>"]
edition = "2018"
name = "arch-db-meta-rs"
version = "0.1.0"

[dependencies]
alpm = "2.0"
serde_json = "^1.0.59"
symlink = "^0.1.0"
tempdir = "^0.3.7"

[dependencies.serde]
features = ["derive"]
version = "^1.0.117"
